import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ChakraProvider, theme } from '@chakra-ui/react'
import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className='relative overflow-hidden '>
            <ChakraProvider>
                <Navbar />
                <body className={inter.className} >
                    {children}
                </body>
                <Footer />
            </ChakraProvider>
        </html>
    );
}
